import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar";
import { Providers } from "./providers";
import { usePathname } from "next/navigation";
import { SessionProvider } from "next-auth/react";
import NextAuth from "@/lib/next-auth/NextAuth";


const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuth>
        <Providers>
        <Navbar />
        {children}
        </Providers>
        </NextAuth>
        </body>
    </html>
  );
}
